version: '3.8'

services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: npx expo start --host 0.0.0.0 --port 8081
    # volumes:
    #   - .:/app
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0