services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    command: npx expo start --port 8084
    # volumes:
    #   - .:/app
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0