services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: npx expo start --port 8083
    # volumes:
    #   - .:/app
    environment:
      - NODE_ENV=development